package event.mangement.system;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Akila Benaragama
 */
public class Eventregistration extends javax.swing.JFrame {

    /**
     * Creates new form Eventregistration
     */
    public Eventregistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        location_search = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        event_list = new javax.swing.JComboBox<>();
        visit_label = new javax.swing.JLabel();
        site_button = new javax.swing.JButton();
        registration_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        location_search.setText("Location");
        getContentPane().add(location_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 54, 129, -1));

        search_button.setBackground(new java.awt.Color(0, 0, 0));
        search_button.setForeground(new java.awt.Color(255, 255, 255));
        search_button.setText("Search");
        getContentPane().add(search_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 54, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 106, -1, -1));

        description.setColumns(20);
        description.setRows(5);
        description.setText("A breathe of fresh air in the world of Event. Eventura will provide \nthe best solution in Sri lanka. Seat comforte and enjoy your life \ntime moments with us. ");
        jScrollPane1.setViewportView(description);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 97, 612, 64));

        event_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sport ", "Musical", "Religious", "Drama", " " }));
        event_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                event_listActionPerformed(evt);
            }
        });
        getContentPane().add(event_list, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 54, 387, -1));

        visit_label.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        visit_label.setText("Visit Us!");
        getContentPane().add(visit_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 480, -1, 24));

        site_button.setBackground(new java.awt.Color(0, 0, 0));
        site_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        site_button.setForeground(new java.awt.Color(255, 255, 255));
        site_button.setText("www.Evntura.com");
        site_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                site_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(site_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, -1, -1));

        registration_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        registration_button.setText("Register your own event");
        registration_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        registration_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registration_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(registration_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 170, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 640, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void event_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_event_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_event_listActionPerformed

    private void site_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_site_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_site_buttonActionPerformed

    private void registration_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registration_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registration_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eventregistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eventregistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eventregistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eventregistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eventregistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea description;
    private javax.swing.JComboBox<String> event_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField location_search;
    private javax.swing.JButton registration_button;
    private javax.swing.JButton search_button;
    private javax.swing.JButton site_button;
    private javax.swing.JLabel visit_label;
    // End of variables declaration//GEN-END:variables
}
