package event.mangement.system;


import event.mangement.system.Dashboard;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LENOVO
 */
public class signin extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public signin() {
       
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollBar2 = new javax.swing.JScrollBar();
        jScrollBar3 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        signuppanel = new javax.swing.JPanel();
        email = new javax.swing.JLabel();
        signup_label = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        E1 = new javax.swing.JTextField();
        password_signin = new javax.swing.JPasswordField();
        signin_button = new javax.swing.JButton();
        Type = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(254, 248, 243));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(1220, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signuppanel.setBackground(new java.awt.Color(255, 255, 255));
        signuppanel.setPreferredSize(new java.awt.Dimension(1210, 768));

        email.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        email.setText("E-mail");

        signup_label.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        signup_label.setText("Sign In");

        password.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        password.setText("Password");

        password_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_signinActionPerformed(evt);
            }
        });

        signin_button.setBackground(new java.awt.Color(0, 0, 255));
        signin_button.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        signin_button.setForeground(new java.awt.Color(255, 255, 255));
        signin_button.setText("Sign In");
        signin_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_buttonActionPerformed(evt);
            }
        });

        Type.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Organizer", "ADMIN" }));

        javax.swing.GroupLayout signuppanelLayout = new javax.swing.GroupLayout(signuppanel);
        signuppanel.setLayout(signuppanelLayout);
        signuppanelLayout.setHorizontalGroup(
            signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signuppanelLayout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addGroup(signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signuppanelLayout.createSequentialGroup()
                        .addGroup(signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(signuppanelLayout.createSequentialGroup()
                                .addComponent(email)
                                .addGap(242, 242, 242))
                            .addGroup(signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(password)
                                .addComponent(E1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                .addComponent(password_signin)
                                .addComponent(Type, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signuppanelLayout.createSequentialGroup()
                        .addComponent(signin_button)
                        .addGap(246, 246, 246))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signuppanelLayout.createSequentialGroup()
                        .addComponent(signup_label)
                        .addGap(223, 223, 223))))
        );
        signuppanelLayout.setVerticalGroup(
            signuppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signuppanelLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(signup_label)
                .addGap(87, 87, 87)
                .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(email)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(E1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(signin_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        jPanel1.add(signuppanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 610, 770));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eventura-high-resolution-logo.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane3.setMaximumSize(new java.awt.Dimension(3, 3));
        jScrollPane3.setPreferredSize(new java.awt.Dimension(1210, 768));
        jScrollPane3.setVerticalScrollBar(jScrollBar2);
        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void password_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_signinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_signinActionPerformed

    private void signin_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_buttonActionPerformed
        // TODO add your handling code here:
        
            String URL = "jdbc:mysql://127.0.0.1:3307/event_management";
            String USER = "root";
            String PASSWORD = "12345678Apb";
        
        
        try{
            
            String sql="";
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection c1=DriverManager.getConnection(URL, USER,PASSWORD);
            
            String role = Type.getSelectedItem().toString();
            if(role=="User"){
               sql = "SELECT UID,Position,Name FROM users WHERE Email = ? AND Password = ? AND Position = ? ";
            }else if(role=="Organizer"){
               sql = "SELECT OrgID,Position,Name FROM organizers WHERE Email = ? AND Password = ? AND Position = ? ";
            }else if(role=="ADMIN"){
               sql = "SELECT AdminID,Position,Name FROM admin WHERE Email = ? AND Password = ? AND Position = ? ";
            }
            
            PreparedStatement st = c1.prepareStatement(sql);
            
            st.setString(1,E1.getText().trim());
            st.setString(2, password_signin.getText().trim());
            st.setString(3, Type.getSelectedItem().toString());
            ResultSet resultSet = st.executeQuery();
            
            if (resultSet.next()){
               
              
            
               /* id=resultSet.getInt(1);
                name=resultSet.getString(3);
                System.out.println(name);
                */
                if(role=="User"){
                    
                User_Profile sM=new User_Profile();
                this.setVisible(false);
                sM.setVisible(true);
                JOptionPane.showMessageDialog(null, "Successfully loged in !!!");
                c1.close();
            }
               
               else if(role=="ADMIN"){
                Admin_Profile sI=new Admin_Profile();
                this.setVisible(false);
                sI.setVisible(true);
                JOptionPane.showMessageDialog(null, "Successfully loged in !!!");
                c1.close();
            }
                
              else  if(role=="Organizer"){
                Organizer_Profile sS=new Organizer_Profile();
                this.setVisible(false);
                sS.setVisible(true);
                JOptionPane.showMessageDialog(null, "Successfully loged in !!!");
                c1.close();
            }
                
                
               
               
               
                
                
            }else{
            
            JOptionPane.showMessageDialog(null, "Failed to Log In");
                c1.close();
            }
            
        }
        catch(Exception e){
        
            System.out.println(e);
            
        }
        
        
        
        
        
        
    }//GEN-LAST:event_signin_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField E1;
    private javax.swing.JComboBox<String> Type;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollBar jScrollBar3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField password_signin;
    private javax.swing.JButton signin_button;
    private javax.swing.JLabel signup_label;
    private javax.swing.JPanel signuppanel;
    // End of variables declaration//GEN-END:variables
}
